nexus:
  - name: nexus
    music: default_track.mp3
  - name: vault
    music: default_track.mp3
  - name: pet_yard
    music: default_track.mp3
  - name: guild_hall
    music: default_track.mp3

realm:
  - name: oceanic
    music: default_track.mp3
  - name: sprite_forest
    music: default_track.mp3
  - name: haunted_hallows
    music: default_track.mp3
  - name: shipwreck_cove
    music: default_track.mp3
  - name: dead_church
    music: default_track.mp3
  - name: risen_hell
    music: default_track.mp3
  - name: abandoned_city_outer
    music: default_track.mp3
  - name: abandoned_city_inner
    music: default_track.mp3
  - name: abyssal
    music: default_track.mp3
  - name: prehistoric
    music: default_track.mp3
  - name: floral
    music: default_track.mp3
  - name: sanguine
    music: default_track.mp3
  - name: frozen
    music: default_track.mp3
  - name: frosty
    music: default_track.mp3
  - name: relentless_springs
    music: default_track.mp3

dungeon:
  - name: Pirate Cave
    music: default_track.mp3
    
  - name: Forest Maze
    music: default_track.mp3
    
  - name: Spider Den
    music: default_track.mp3
    
  - name: Forbidden Jungle
    music: default_track.mp3
    
  - name: The Hive
    music: default_track.mp3
    
  - name: Snake Pit
    music: default_track.mp3
    
  - name: Sprite World
    music: default_track.mp3
    
  - name: Cave of a Thousand Treasures
    music: default_track.mp3
    
  - name: Ancient Ruins
    music: default_track.mp3
    
  - name: Magic Woods
    music: default_track.mp3
    
  - name: Candyland Hunting Grounds
    music: default_track.mp3
    
  - name: Undead Lair
    music: default_track.mp3
    
  - name: Pupper Master's Theatre
    music: default_track.mp3
    
  - name: Toxic Sewers
    music: default_track.mp3
    
  - name: Cursed Library
    music: default_track.mp3
    
  - name: Mad Lab
    music: default_track.mp3
    
  - name: Abyss of Demons
    music: default_track.mp3
    
  - name: Manor of the Immortals
    music: default_track.mp3
    
  - name: Haunted Cemetary
    music: default_track.mp3
    
  - name: The Machine
    music: default_track.mp3
    
  - name: The Inner Workings
    music: default_track.mp3
    
  - name: Davy Jones' Locker
    music: default_track.mp3
    
  - name: Ice Cave
    music: default_track.mp3
    
  - name: Ocean Trench
    music: default_track.mp3
    
  - name: The Crawling Depths
    music: default_track.mp3
    
  - name: Woodland Labyrinth
    music: default_track.mp3
    
  - name: Deadwater Docks
    music: default_track.mp3
    
  - name: Puppet Master's Encore
    music: default_track.mp3
    
  - name: Cnidarian Reef
    music: default_track.mp3
    
  - name: Parasite Chambers
    music: default_track.mp3
    
  - name: Sulfurous Wetlands
    music: default_track.mp3
    
  - name: Mountain Temple
    music: default_track.mp3
    
  - name: Lair of Draconis
    music: default_track.mp3
    
  - name: Tomb of the Ancients
    music: default_track.mp3
    
  - name: The Third Dimension
    music: default_track.mp3
    
  - name: Lair of Shaitan
    music: default_track.mp3
    
  - name: Secluded Thicket
    music: default_track.mp3
    
  - name: High Tech Terror
    music: default_track.mp3
    
  - name: Moonlight Village
    music: default_track.mp3
    
  - name: The Tavern
    music: default_track.mp3
    
  - name: The Nest
    music: default_track.mp3
    
  - name: Advanced Nest
    music: default_track.mp3
    
  - name: Cultist Hideout
    music: default_track.mp3
    
  - name: Fungal Cavern
    music: default_track.mp3
    
  - name: Crystal Cavern
    music: default_track.mp3
    
  - name: Spectral Penitentiary
    music: default_track.mp3
    
  - name: Kogbold Steamworks
    music: default_track.mp3
    
  - name: Advanced Kogbold Steamworks
    music: default_track.mp3
    
  - name: Lost Halls
    music: default_track.mp3
    
  - name: The Void
    music: default_track.mp3
    
  - name: The Shatters
    music: default_track.mp3

oryx:
  - name: Court of Oryx
  - name: Oryx's Castle
  - name: Oryx's Chamber
  - name: Wine Cellar
  - name: Oryx's Sanctuary

special_zones:
  - name: Beachzone
    music: default_track.mp3
    
  - planets:
    - Malogia
    - Untaris
    - Katalund
    - Forax
  - heroic_versions:
    - Heroic Undead Lair
    - Heroic Abyss of Demons

  - seasonal_events:
    - Rainbow Road
    - Santa's Workshop
    - Ice Tomb
    - Battle for the Nexus
    - Belladonna's Garden
    - Queen Bunny Chamber
    - Mad God Mayhem
    - White Snake Invasion I
    - The Trails of Cronus
    - Hidden Interregnum
    - White Snake Invasion II
    - White Snake Invasion III

  - miscellaneous:
    - Tutorial
    - Oryx's Kitchen
    - Chess
    - Admin Arena
